version: '3.1'

services: 
    db: 
        image: mariadb/server:latest
        container_name: mariadbtest
        restart: always
        env_file: 
            - db.env
        networks: 
            - projectNetwork
            
    web: 
        image: apache:latest
        build: ./webapp
        depends_on: 
            - db
        container_name: webServer
        ports: 
            - "8080:80"
        restart: always
        env_file: 
            - web.env
        networks: 
            - projectNetwork
            
networks: 
    projectNetwork: 
